from django.core.management.base import BaseCommand
from tasks.models import Task
from user_app.models import HeroUser

class Command(BaseCommand):
  def handle(self, *args, **options):
    HeroUser.objects.bulk_create([
      HeroUser(username='LuisPayne', first_name='Luis', last_name='Payne', email="Luis@ihero.com", password='password1', website="http://website1.com", bio="Aliquam erat volutpat. Proin lacinia velit vitae molestie congue. Maecenas tempus porttitor blandit. Sed consequat vehicula facilisis. Morbi bibendum finibus ex at euismod. Vestibulum suscipit, sem et rhoncus efficitur.", age='34', interests="Service Industry", is_coach=True, is_staff=True),
      HeroUser(username='LeonelBurch', first_name='Leonel', last_name='Burch', email="Leonel@ihero.com", password='password1', website="http://website1.com", bio="Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque tempus, urna non ultricies semper, nunc est placerat nisi, a dignissim justo arcu eu urna. Proin non mi eu ex mattis eleifend in id justo.", age='37', interests="Sales", is_coach=True, is_staff=True),
      HeroUser(username='VanceShields', first_name='Vance', last_name='Shields', email="Vance@ihero.com", password='password1', website="http://website1.com", bio="Proin ullamcorper auctor fringilla. Aliquam placerat aliquam ligula vel lacinia. Morbi vel odio quis arcu euismod dictum id sit amet purus. Sed lacus mi, consequat ac cursus nec, bibendum et mi. ", age='40', interests="Health Care", is_coach=True, is_staff=True),
      HeroUser(username='LianaClarke', first_name='Liana', last_name='Clarke', email="Liana@ihero.com", password='password1', website="http://website1.com", bio="Nulla dapibus nibh at diam ultricies posuere. Etiam eleifend dictum faucibus. Aenean hendrerit pharetra aliquam. Donec accumsan egestas pellentesque. Nullam eu felis magna. Nullam eget metus erat.", age='30', interests="Technology", is_coach=True, is_staff=True),
      HeroUser(username='RainaChase', first_name='Raina', last_name='Chase', email="Raina@ihero.com", password='password1', website="http://website1.com", bio="Nunc sed lorem eget dui pharetra aliquet ut vitae risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce accumsan nulla eget enim auctor rhoncus.", age='45', interests="Finance", is_coach=True, is_staff=True),
      HeroUser(username='LawsonNavarro', first_name='Lawson', last_name='Navarro', email="Lawson@ihero.com", password='password1', website="http://website1.com", bio="Nulla non auctor erat. Vivamus cursus luctus mauris, at fringilla est consectetur sed. Suspendisse id consequat sapien. Quisque blandit sollicitudin vulputate. Integer id massa id enim efficitur aliquet.", age='18', interests="Education", is_coach=True, is_staff=True),
      HeroUser(username='KeithChung', first_name='Keith', last_name='Chung', email="Keith@ihero.com", password='password1', website="http://website1.com", bio=" Integer ullamcorper, tellus non interdum molestie, est ipsum eleifend eros, in varius nulla est ut risus. Donec ullamcorper rhoncus tortor nec tempus.", age='24', interests="Service Industry"),
      HeroUser(username='RhysZamora', first_name='Rhys', last_name='Zamora', email="Rhys@ihero.com", password='password1', website="http://website1.com", bio="Donec iaculis eros et mauris suscipit aliquam. Donec pellentesque diam at posuere laoreet. Vivamus sed suscipit neque.", age='23', interests="Service Industry"),
      HeroUser(username='PaulaFlores', first_name='Paula', last_name='Flores', email="Paula@ihero.com", password='password1', website="http://website1.com", bio="Maecenas commodo finibus neque laoreet accumsan. Maecenas ac nisi lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus dapibus eleifend justo, quis suscipit leo faucibus vel. ", age='29', interests="Sales"),
      HeroUser(username='LukaHuynh', first_name='Luka', last_name='Huynh', email="Luka@ihero.com", password='password1', website="http://website1.com", bio="Donec efficitur, erat at vehicula viverra, nibh felis ornare mauris, quis fringilla nunc est a quam. Maecenas rutrum faucibus elit at gravida. Interdum et malesuada fames ac ante ipsum primis in faucibus. ", age='26', interests="Sales"),
      HeroUser(username='EmilianoAnderson', first_name='Emiliano', last_name='Anderson', email="Emiliano@ihero.com", password='password1', website="http://website1.com", bio="Sem felis varius massa, ac interdum urna magna vel nisl. Vivamus sollicitudin metus nec ex suscipit, vel tincidunt velit semper. Nam cursus consequat risus, eu pellentesque lectus faucibus vitae.", age='34', interests="Health Care"),
      HeroUser(username='BarrettHaley', first_name='Barrett', last_name='Haley', email="Barrett@ihero.com", password='password1', website="http://website1.com", bio="Donec hendrerit sagittis risus, in blandit enim posuere gravida. In imperdiet elementum enim a aliquet. Curabitur placerat, lectus ac fringilla iaculis, orci dolor tincidunt enim, in tincidunt tortor nunc ut est.", age='44', interests="Health Care"),
      HeroUser(username='KelseyWebb', first_name='Kelsey', last_name='Webb', email="Kelsey@ihero.com", password='password1', website="http://website1.com", bio="Aenean at efficitur nibh. Donec non pharetra magna, quis viverra diam. Maecenas lobortis ornare nisl.", age='52', interests="Technology"),
      HeroUser(username='AgustinBenson', first_name='Agustin', last_name='Benson', email="Agustin@ihero.com", password='password1', website="http://website1.com", bio="Proin tempor gravida nunc, ac luctus est mattis non. Suspendisse rhoncus dui tortor, id interdum felis vehicula sed. Etiam tristique felis vitae risus rhoncus, vel iaculis nibh pharetra. Nullam facilisis.", age='38', interests="Technology"),
      HeroUser(username='JenniferOrtiz', first_name='Jennifer', last_name='Ortiz', email="Jennifer@ihero.com", password='password1', website="http://website1.com", bio="Aenean consectetur massa felis, sit amet condimentum dui porta sit amet. Nullam vel ultrices leo, sed lacinia turpis. In non placerat odio, vitae varius ipsum. Duis ipsum est, faucibus in.", age='35', interests="Finance"),
      HeroUser(username='LoreleiAtkinson', first_name='Lorelei', last_name='Atkinson', email="Lorelei@ihero.com", password='password1', website="http://website1.com", bio="Aenean ornare egestas sapien id pellentesque. Cras laoreet a magna et interdum. Vivamus finibus purus nec pharetra tristique. Praesent et felis hendrerit, pellentesque ante quis, posuere felis. Duis fermentum sed.", age='26', interests="Finance"),
      HeroUser(username='AddisynKhan', first_name='Addisyn', last_name='Khan', email="Addisyn@ihero.com", password='password1', website="http://website1.com", bio="Donec euismod risus quis dolor accumsan lacinia at sit amet eros. Nullam euismod sapien et purus pretium suscipit. Etiam condimentum lacinia sapien ac porta. Nunc sagittis massa id justo accumsan.", age='21', interests="Education"),
    ])

    Task.objects.bulk_create([
      Task(task="Take a Kickboxing Class", assigned_to=HeroUser.objects.get(username='LuisPayne'), completed=True),
      Task(task="Learn to Play Chess", assigned_to=HeroUser.objects.get(username='LuisPayne'), completed=True),
      Task(task="Learn a New Language and Speak It Fluently", assigned_to=HeroUser.objects.get(username='LuisPayne')),
      Task(task="Join a Running Club", assigned_to=HeroUser.objects.get(username='LeonelBurch'), completed=True),
      Task(task="Learn to Say Exactly What I Mean", assigned_to=HeroUser.objects.get(username='LeonelBurch'), completed=True),
      Task(task="Read a Book More Than 5 Times", assigned_to=HeroUser.objects.get(username='LeonelBurch')),
      Task(task="Join a Yoga Class", assigned_to=HeroUser.objects.get(username='VanceShields'), completed=True),
      Task(task="Attend a Writing Class", assigned_to=HeroUser.objects.get(username='VanceShields'), completed=True),
      Task(task="Make a High Quality Film", assigned_to=HeroUser.objects.get(username='VanceShields')),
      Task(task="Complete a Cross-Country Ski Race", assigned_to=HeroUser.objects.get(username='LianaClarke'), completed=True),
      Task(task="Learn the Art of Small Talk", assigned_to=HeroUser.objects.get(username='LianaClarke'), completed=True),
      Task(task="Build a Tree House", assigned_to=HeroUser.objects.get(username='LianaClarke')),
      Task(task="Join a Gym", assigned_to=HeroUser.objects.get(username='RainaChase'), completed=True),
      Task(task="Learn to Ride and Care For Horses", assigned_to=HeroUser.objects.get(username='RainaChase'), completed=True),
      Task(task="Act in a Short Film", assigned_to=HeroUser.objects.get(username='RainaChase')),
      Task(task="Go Tandem Bike Riding", assigned_to=HeroUser.objects.get(username='LawsonNavarro'), completed=True),
      Task(task="Speak In front of 10+ People", assigned_to=HeroUser.objects.get(username='LawsonNavarro'), completed=True),
      Task(task="Study new information", assigned_to=HeroUser.objects.get(username='LawsonNavarro')),
      Task(task="Go Mountain Climbing", assigned_to=HeroUser.objects.get(username='KeithChung'), completed=True),
      Task(task="Complete a Rubik's Cube", assigned_to=HeroUser.objects.get(username='KeithChung'), completed=True),
      Task(task="Exercise Daily in the Morning", assigned_to=HeroUser.objects.get(username='KeithChung')),
      Task(task="Run a Half-Marathon With my Mom", assigned_to=HeroUser.objects.get(username='RhysZamora'), completed=True),
      Task(task="Learn How to Cook Something Difficult", assigned_to=HeroUser.objects.get(username='RhysZamora'), completed=True),
      Task(task="Set Up a Non-Profit", assigned_to=HeroUser.objects.get(username='RhysZamora')),
      Task(task="Accomplish Three Pull-Ups", assigned_to=HeroUser.objects.get(username='PaulaFlores'), completed=True),
      Task(task="Learn a Computer Programming Language", assigned_to=HeroUser.objects.get(username='PaulaFlores'), completed=True),
      Task(task="Break a Bad Habit", assigned_to=HeroUser.objects.get(username='PaulaFlores')),
      Task(task="Complete 4Hr Body Challenge", assigned_to=HeroUser.objects.get(username='LukaHuynh'), completed=True),
      Task(task="Learn Morse Code", assigned_to=HeroUser.objects.get(username='LukaHuynh'), completed=True),
      Task(task="Turn a Passion Into a Way to Make Money", assigned_to=HeroUser.objects.get(username='LukaHuynh')),
      Task(task="Swim in a Lake", assigned_to=HeroUser.objects.get(username='EmilianoAnderson'), completed=True),
      Task(task="Eat Healthy and Home Made Food", assigned_to=HeroUser.objects.get(username='EmilianoAnderson'), completed=True),
      Task(task="Sculpt Something from Modeling Clay", assigned_to=HeroUser.objects.get(username='EmilianoAnderson')),
      Task(task="Increase my Flexibility", assigned_to=HeroUser.objects.get(username='BarrettHaley'), completed=True),
      Task(task="Do a Course in Music", assigned_to=HeroUser.objects.get(username='BarrettHaley'), completed=True),
      Task(task="Donate Things to the Animal Shelter", assigned_to=HeroUser.objects.get(username='BarrettHaley')),
      Task(task="Play Golf For a Day", assigned_to=HeroUser.objects.get(username='KelseyWebb')),
      Task(task="Spread positivity", assigned_to=HeroUser.objects.get(username='KelseyWebb'), completed=True),
      Task(task="Learn to Change the Oil", assigned_to=HeroUser.objects.get(username='KelseyWebb'), completed=True),
      Task(task="Spend a Day Riding Horses", assigned_to=HeroUser.objects.get(username='AgustinBenson')),
      Task(task="Help Out at a Homeless Shelter", assigned_to=HeroUser.objects.get(username='AgustinBenson'), completed=True),
      Task(task="Learn How to Change a Tire", assigned_to=HeroUser.objects.get(username='AgustinBenson'), completed=True),
      Task(task="Complete a Half Marathon", assigned_to=HeroUser.objects.get(username='JenniferOrtiz')),
      Task(task="Complete a Management Course", assigned_to=HeroUser.objects.get(username='JenniferOrtiz'), completed=True),
      Task(task="Learn Basic Car Maintenance", assigned_to=HeroUser.objects.get(username='JenniferOrtiz'), completed=True),
      Task(task="Compete in an Archery Tournament", assigned_to=HeroUser.objects.get(username='LoreleiAtkinson')),
      Task(task="Create Passive Income", assigned_to=HeroUser.objects.get(username='LoreleiAtkinson'), completed=True),
      Task(task="Make a Quotes Board", assigned_to=HeroUser.objects.get(username='LoreleiAtkinson'), completed=True),
      Task(task="Start a Steady Exercise Routine", assigned_to=HeroUser.objects.get(username='AddisynKhan')),
      Task(task="Meet a Millionaire", assigned_to=HeroUser.objects.get(username='AddisynKhan'), completed=True),
      Task(task="Add Something Useful to Wikipedia", assigned_to=HeroUser.objects.get(username='AddisynKhan'), completed=True),
    ])