# Generated by Django 3.2.5 on 2021-07-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herouser',
            name='interests',
            field=models.CharField(choices=[('Service Industry', 'Service Industry'), ('Technology', 'Technology'), ('Sales', 'Sales'), ('Health Care', 'Health Care'), ('Finance', 'Finance'), ('Education', 'Education')], default='Technology', max_length=20),
        ),
    ]
